# 定义多语言文本映射
LANGUAGES = {
    'zh': {
        'title': '逸超超声助手',
        'ask_button': '提问',
        'clear_conversion_button': '清除会话',
        'capture_screen_button': '截屏',
        'chinese_rb': '中文',
        'english_rb': 'English',
        'history_button': '历史对话',
        'welcome_message': '你好, 我是逸超智能助手',
        'error': '错误',
        'warning': '警告',
        'close': '关闭',
        'user': '用户',
        'assistant': '助手',
        'image': '图片',
        'success': '成功',
        'config': '配置',
        'chat_viewer': '聊天会话查看器',
        'chat_view_export_image_failed': '导出图片失败',
        'chat_view_load_image_failed': '加载图片失败',
        'chat_view_search': '输入关键词进行搜索',
        'chat_view_delete_selected_session': '删除选中项',
        'chat_view_load_session_error': '加载会话失败',
        'chat_view_session_not_found': '会话不存在',
        'chat_view_session_deleted': '所选会话不存在或已被删除',
        'chat_view_load_session_detail_error': '加载会话详情失败',
        'chat_view_export_to_word': '导出为Word',
        'chat_view_no_selected': '无选中项',
        'chat_view_choose_session': '请选择要删除的会话',
        'chat_view_confirm': '确认删除',
        'chat_view_confirm_delete_session': '确定要删除选中的会话吗',
        'chat_view_select_a_session': '请先选择一个会话',
        'chat_view_chat_message': '聊天记录',
        'chat_view_save_word': '保存Word文档',
        'chat_view_save_word_to': '文档已保存到',
        'chat_view_save_word_failed': '保存Word文档失败',
        'image_gallery_add_image': '添加图片',
        'image_gallery_image_already_exist': '图片已存在',
        'image_gallery_max_image_number_1': '目前最多只支持',
        'image_gallery_max_image_number_2': '张图片',
        'image_gallery_unable_to_load_image': '无法处理文件',
        'rag_mode': '文本检索增强(RAG)',
        'confirm': '确认',
    },
    'en': {
        'title': 'eSonic Ultrasound Assistant',
        'ask_button': 'Ask',
        'clear_conversion_button': 'Clear',
        'capture_screen_button': 'Capture Screen',
        'chinese_rb': 'Chinese',
        'english_rb': 'English',
        'history_button': 'History',
        'welcome_message': 'Hi, I\'m eSonic AI assistant',
        'error': 'Error',
        'warning': 'Warning',
        'close': 'Close',
        'user': 'User',
        'assistant': 'Assistant',
        'image': 'Image',
        'success': 'Success',
        'config': 'Configuration',
        'chat_viewer': 'Chat browser',
        'chat_view_export_image_failed': 'Failed to export the image',
        'chat_view_load_image_failed': 'Failed to load the image',
        'chat_view_search': 'Enter keywords to search',
        'chat_view_delete_selected_session': 'Delete selected item',
        'chat_view_load_session_error': 'Failed to load the conversation',
        'chat_view_session_not_found': 'Conversation not found',
        'chat_view_session_deleted': 'The selected conversation does not exist or has been deleted',
        'chat_view_load_session_detail_error': 'Failed to load the conversation details',
        'chat_view_export_to_word': 'Export to Word',
        'chat_view_no_selected': 'No item selected',
        'chat_view_choose_session': 'Please select a conversation to delete',
        'chat_view_confirm': 'Confirm deletion',
        'chat_view_confirm_delete_session': 'Are you sure you want to delete the selected conversation?',
        'chat_view_select_a_session': 'Select a session',
        'chat_view_chat_message': 'Chat history',
        'chat_view_save_word': 'Save Word document',
        'chat_view_save_word_to': 'The document has been saved to',
        'chat_view_save_word_failed': 'Save word failed',
        'image_gallery_add_image': 'Add image',
        'image_gallery_image_already_exist': 'Image already exist',
        'image_gallery_max_image_number_1': 'Currently max image number is ',
        'image_gallery_max_image_number_2': '',
        'image_gallery_unable_to_load_image': 'Unable to load image',
        'rag_mode': 'RAG mode',
        'confirm': 'Confirm',
    }
}